# Generated by Django 3.2.25 on 2024-05-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodemodel',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
